### ISSUE TITLE
List of dependencies not included in documentation

### ISSUE THREAD

**Issue by jessie-dotson** [KathrynJones1/catwoman#10]
The pip install worked like a charm for me.  But JOSS recommends that the documentation include a list of dependencies.  Recommend adding that list to the install documentation page.  (With other packages it's been super-useful to have that list include the minimum version # of the required packages as well as just the list...)

**Comment by jessie-dotson** [comment]
Ok, sorry to back on this one...  But I do think the package needs to list the minimum required version number for the dependencies.  I installed catwoman on another laptop that I only use occasionally.  It had an older version of numpy (1.16.2).  Catwoman installed cleanly, but it wouldn't run.   It threw an error when called catwoman.TransitModel.  Updating my numpy fixed the error.

**Comment by KathrynJones1** [comment]
Hi @jessie-dotson , so I've had a look and I've edited the pyproject.toml file (that was recommended in https://github.com/KathrynJones1/catwoman/issues/2 ) so that it specifies that the numpy version is >=1.16.2, which is the version I have on my laptop at the moment and it is able to run `catwoman` (so I'm not sure why the same version wouldn't work on yours?) . I've tested that if you try and download the latest `catwoman` (version 1.0.11) then it will reinstall an updated numpy. Do you think this is sufficient as an automatic process or do you think it requires an explicit list?

**Comment by jessie-dotson** [comment]
This makes sense.  I didn't keep enough bread crumbs around to recreate my error.  (doh!)  Thank you for double checking on your system!

**Comment by KathrynJones1** [comment]
@jessie-dotson are you happy for me to close this issue? :)

**Comment by jessie-dotson** [comment]
Yes, please go ahead and close the issue!
